name: CI - Linux
on: [push, pull_request, workflow_dispatch]

jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            ref: "main"
        - name: Build Docker Image
          run: .\linux.ps1
          shell: pwsh