name: Windows 3.x
on: 
    workflow_dispatch:

jobs:
    build:
      name: Build
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
          with:
            ref: "3"
        - name: Build Docker Image
          run: .\src\docker\windows-core\build.ps1
          shell: pwsh
        - name: Push Docker Image
          run: .\src\docker\windows-core\push.ps1
          env:
            dockerpassword: ${{ secrets.DOCKER_PASSWORD }}
          shell: pwsh